### ISSUE TITLE
Exception thrown when scrolling beyond end of stream

### ISSUE THREAD

**Issue by Mgamerz** [abbaye/WpfHexEditorControl#30]
This is triggered on latest nuget package.

## Expected Behavior
I should not be able to scroll farther down than the number of bytes shown in the list, in accordance with the byteperline attribute. This is done when passing in a MemoryStream (I am not using file-based stuff for this, and I will be making heavy use of byte[] arrays that I am converting to stream.).

## Actual Behavior
When I scroll down farther than I should be able to, the input stream tries to read beyond the bounds and throws an exception. I get the stack trace as shown below at the bottom of this post. This only seems to be triggered if you don't first click the up/down arrows.

## Steps to Reproduce the Problem
1. Load a byte[] array containing some bytes. In this case I have 11 bytes through a MemoryStream as shown in the following picture.

![image](https://user-images.githubusercontent.com/2738836/39411557-ba2a987e-4bc9-11e8-9c6b-7ec89f6a67a5.png)

2. Attempt to scroll down using the little bar part that is draggable. As you can see the scrollbar makes it look like it can scroll for a huge ways when it really can't scroll at all. (Correction - it can scroll 3 down, but the bar size does not change to reflect this and is somewhat misleading).
3. It throws an exception. In this instance it triggers my exception handler I am using during our migration from winforms to wpf.
![image](https://user-images.githubusercontent.com/2738836/39411571-e78badda-4bc9-11e8-9239-c53b00cb69ba.png)

Posted stacktrace is as follows.
```
ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at WpfHexaEditor.HexEditor.UpdateViewers(Boolean controlResize)
   at WpfHexaEditor.HexEditor.RefreshView(Boolean controlResize, Boolean refreshData)
   at WpfHexaEditor.HexEditor.VerticalScrollBar_ValueChanged(Object sender, RoutedPropertyChangedEventArgs`1 e)
   at System.Windows.RoutedPropertyChangedEventArgs`1.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.RangeBase.OnValueChanged(Double oldValue, Double newValue)
   at System.Windows.Controls.Primitives.RangeBase.OnValueChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.ScrollBar.ChangeValue(Double newValue, Boolean defer)
   at System.Windows.Controls.Primitives.ScrollBar.UpdateValue(Double horizontalDragDelta, Double verticalDragDelta)
   at System.Windows.Controls.Primitives.ScrollBar.OnThumbDragDelta(Object sender, DragDeltaEventArgs e)
   at System.Windows.Controls.Primitives.DragDeltaEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.Thumb.OnMouseMove(MouseEventArgs e)
   at System.Windows.UIElement.OnMouseMoveThunk(Object sender, MouseEventArgs e)
   at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by abbaye** [comment]
I will check it`s soon as possible

**Comment by abbaye** [comment]
The bug is fixed :)
